### ISSUE TITLE
way around for "find_by"

### ISSUE THREAD

**Issue by Bilal-Abbas** [zammad/zammad-api-client-ruby#6]
what if we want to find a user by email or by first or last name without passing the id as we do in rails console from your gem?

**Comment by thorsteneckel** [comment]
Hey @Bilal-Abbas you have to use the search endpoint for this. You can do it like this `client.user.search(query: 'email:findme@example.com')`. Please be aware that **this will return an array**!

**Comment by Bilal-Abbas** [comment]
.search gave me multiple objects as you have mentioned earlier that .search gave me an array
What if I had to update a specific organization.


```
client = ZammadAPI::Client.new(url:'https://*****', user:'*****',password:'*****')

zammad_organization = client.organization.search(query: user.try(:company).try(:ext_reference_domain))


if zammad_organization.count.present? and zammad_organization.count > 0
    zammad_organization = zammad_organization.first
else
    zammad_organization = client.organization.new()
 end


zammad_organization.name = user.try(:company).try(:name) || ""

zammad_organization.domain = user.try(:company).try(:ext_reference_domain)

zammad_organization.save

```
.search gave me a count of two but I need to update my specific organization.

Any help regarding that?

**Comment by thorsteneckel** [comment]
Hey @Bilal-Abbas - I think the root cause is that your search query is ambiguous. 

From what I see is that `user.company.ext_reference_domain` is used to lookup the matching Zammad Organization. Why does this reference domain search returns multiple results? It's hard to tell for me because I lack of the domain knowledge. You should either use the [advanced (Elasticsearch) options](https://user-docs.zammad.org/en/latest/advanced/search.html) or iterate over the result of the search and do a programmatic check on which one is the actual one you are looking for.

**Comment by Bilal-Abbas** [comment]
Thanks, man for your reply.
I just figure out a way by following line of code

```
client.organization.search(query: 'name:'+user.try(:company).try(:name))
```

by just adding ```'name:' +``` solve my problem.

Cheers !!!
