### ISSUE TITLE
enable notification tray after creating a ticket by API

### ISSUE THREAD

**Issue by simplilearnuser1** [zammad/zammad-api-client-ruby#7]
Hi,
I have been able to use the zammad ruby api client to create ticket.
Unfortunately when the new ticket is created I don't receive the notification and I only see it in the activity stream :
![2019-11-28_17h48_40](https://user-images.githubusercontent.com/52014628/69822887-b80aad80-1207-11ea-939e-af5e20cadf2c.png)
here is the code I used in the command line to create the ticket :

 **ticket = client.ticket.new(title: 'some new title 4',state: 'new',priority: '2 normal',owner: '-',customer: 'dcyaounde@gmail.com',group: 'Users',article: {sender: 'Customer',type: 'note',subject: 'some subject',content_type: 'text/plain',body: "new ticket \n created by using the zammad ruby API",})**

**Comment by martini** [comment]
Hi @simplilearnuser1 

in Zammad you do not get notifications for actions which you do by your self. I guess you use the same user for the api call as you use for your web session.

If you use an API user or you login with another user you will get notifications.

I'm closing because it's not an API client issue. For user questions please use https://community.zammad.org/

 -Martin

**Comment by simplilearnuser1** [comment]
you are absolutely right @martini I was using the same user for API calls and web access to zammad.
Thanks a lot for your reply.
